-- Payment Service — migração inicial (scaffold T-101).
-- Movimentações, aprovação/estorno e histórico completos chegam em T-103/T-105.

CREATE TABLE carteira (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titular_id VARCHAR(64)    NOT NULL,
    saldo      NUMERIC(18, 2) NOT NULL DEFAULT 0
);
