-- Prontuário Service — migração inicial (scaffold T-101).
-- O schema de domínio completo (consultas, histórico) chega em T-102/T-105.

CREATE TABLE prontuario (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id VARCHAR(64)  NOT NULL,
    criado_em   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
