-- Invoice Service — migração inicial (scaffold T-101).
-- Geração de NF simulada, reprocessamento e listagem completos chegam em T-104/T-105.

CREATE TABLE nota_fiscal (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor   NUMERIC(18, 2) NOT NULL,
    status  VARCHAR(32)    NOT NULL DEFAULT 'PENDENTE'
);
